name: hackwell_taskmanager  # ✅ Renamed to a valid Dart package name
description: A Flutter-based Task Manager app.
publish_to: 'none'  # Prevents accidental publishing

environment:
  sdk: '>=3.0.0 <4.0.0'  # ✅ Updated for newer Dart versions

dependencies:
  flutter:
    sdk: flutter  # ✅ Added Flutter dependency
  web_socket_channel: ^2.4.0  # ✅ Keeping your existing dependency

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true  # ✅ Enables Material Design widgets
