name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install Dependencies
        working-directory: app
        run: flutter pub get

      - name: Analyze Code
        working-directory: app
        run: flutter analyze

     #- name: Run Tests
      # working-directory: app
       #run: flutter test

      - name: Build Web App
        if: github.event_name == 'push'
        working-directory: app
        run: flutter build web --release --target=main.dart
